# Host firewall allowlist for major data TCP (PG/Mongo/Redis/Kafka/MinIO/Influx/Vault/Temporal).
# CIDRs from access-allowlist registry (apps containing "data-plane") + Kind/WG built-ins.
# Emits a PowerShell script artifact; apply on laptop/VPS exposer host (does not call Cloudflare).

terraform {
  required_providers {
    local = {
      source  = "hashicorp/local"
      version = ">= 2.4"
    }
  }
}

variable "registry_path" {
  type = string
}

variable "extra_cidrs" {
  type    = list(string)
  default = []
}

variable "store_ports" {
  type = map(number)
  default = {
    postgres  = 5432
    mongodb   = 27017
    redis     = 6379
    kafka     = 9092
    minio     = 9000
    influx    = 8086
    vault     = 8200
    temporal  = 7233
  }
}

variable "output_script_path" {
  description = "Where to write the generated allowlist script (local_file)."
  type        = string
  default     = ""
}

locals {
  registry = jsondecode(file(var.registry_path))
  entries  = try(local.registry.entries, [])
  from_reg = distinct(flatten([
    for e in local.entries : contains(try(e.apps, []), "data-plane") ? [e.cidr] : []
  ]))
  built_in = ["172.19.0.0/16", "10.77.1.0/24"]
  cidrs    = distinct(concat(local.built_in, local.from_reg, var.extra_cidrs))
  ports    = values(var.store_ports)

  ps1 = <<-EOT
# Generated by terraform module data-plane-ip-allowlist — do not hand-edit.
# Allows store TCP only from registered CIDRs (plus Kind/WG).
$ErrorActionPreference = 'Stop'
$cidrs = @(${join(", ", [for c in local.cidrs : "'${c}'"])})
$ports = @(${join(", ", [for p in local.ports : tostring(p)])})
Write-Host "data-plane allowlist cidrs=$($cidrs -join ',') ports=$($ports -join ',')"
# Windows example (run elevated): New-NetFirewallRule per cidr/port — ops applies per host.
foreach ($cidr in $cidrs) {
  foreach ($port in $ports) {
    $name = "AM-DataPlane-$port-$($cidr -replace '[/\\.]','-')"
    if (-not (Get-NetFirewallRule -DisplayName $name -ErrorAction SilentlyContinue)) {
      New-NetFirewallRule -DisplayName $name -Direction Inbound -Action Allow -Protocol TCP -LocalPort $port -RemoteAddress $cidr | Out-Null
    }
  }
}
EOT
}

resource "local_file" "allowlist_script" {
  count    = var.output_script_path != "" ? 1 : 0
  content  = local.ps1
  filename = var.output_script_path
}

output "allowed_cidrs" {
  value = local.cidrs
}

output "store_ports" {
  value = var.store_ports
}

output "script_preview" {
  value = local.ps1
}
