apiVersion: v1
kind: Service
metadata:
  name: temporal-frontend-nodeport
  namespace: temporal
  labels:
    app.kubernetes.io/name: temporal
    app.kubernetes.io/component: frontend
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: temporal
    app.kubernetes.io/name: temporal
  ports:
    - name: grpc-rpc
      port: 7233
      targetPort: 7233
      nodePort: 30723
