# Setup Grafana MCP for Kind-fleet (https://grafana.asrax.in — bare FQDN hub).
# Creates a Grafana service account token, writes ~/.asrax/credentials.d/grafana-dev.env
# (Cursor launcher name kept for compatibility) with GRAFANA_URL=https://grafana.asrax.in.
#
# Usage (from laptop, after kind-fleet/dev/obs is applied):
#   pwsh -File scripts/setup-grafana-dev-mcp.ps1
# Then in Cursor mcp.json add server "grafana-dev" -> grafana-dev-mcp.cmd and reload MCP.

$ErrorActionPreference = "Stop"
$AsraxHome = if ($env:ASRAX_HOME) { $env:ASRAX_HOME } else { Join-Path $env:USERPROFILE ".asrax" }
$CredDir = Join-Path $AsraxHome "credentials.d"
$BinDir = Join-Path $AsraxHome "bin"
$GrafanaUrl = "https://grafana.asrax.in"

New-Item -ItemType Directory -Force -Path $CredDir | Out-Null

# Admin password from Terraform obs stack (preferred) or Vault
$adminPw = $env:GRAFANA_ADMIN_PASSWORD
if (-not $adminPw) {
  $tfOut = Join-Path $PSScriptRoot "..\terraform\kind-fleet\dev\obs"
  if (Test-Path (Join-Path $tfOut "backend.hcl")) {
    try {
      $adminPw = & terraform "-chdir=$tfOut" output -raw grafana_admin_password 2>$null
    } catch {}
  }
}
if (-not $adminPw -and $env:VAULT_TOKEN) {
  $addr = if ($env:VAULT_ADDR) { $env:VAULT_ADDR } else { "https://vault-dev.asrax.in" }
  try {
    $sec = Invoke-RestMethod -Uri "$addr/v1/apps/data/dev/infra/observability" -Headers @{ "X-Vault-Token" = $env:VAULT_TOKEN }
    $adminPw = $sec.data.data.GRAFANA_ADMIN_PASSWORD
  } catch {}
}
if (-not $adminPw) {
  throw "Set GRAFANA_ADMIN_PASSWORD or apply kind-fleet/dev/obs (terraform output grafana_admin_password)."
}

$pair = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes("admin:$adminPw"))
$h = @{ Authorization = "Basic $pair"; "Content-Type" = "application/json" }

$sas = Invoke-RestMethod -Uri "$GrafanaUrl/api/serviceaccounts/search?query=am-mcp-fleet-dev" -Headers $h
$sa = @($sas.serviceAccounts | Where-Object { $_.name -eq "am-mcp-fleet-dev" }) | Select-Object -First 1
if (-not $sa) {
  $sa = Invoke-RestMethod -Method Post -Uri "$GrafanaUrl/api/serviceaccounts" -Headers $h -Body (@{
      name = "am-mcp-fleet-dev"; role = "Admin"; isDisabled = $false
    } | ConvertTo-Json)
  Write-Host "created service account am-mcp-fleet-dev id=$($sa.id)"
} else {
  Write-Host "using service account id=$($sa.id)"
}

$token = Invoke-RestMethod -Method Post -Uri "$GrafanaUrl/api/serviceaccounts/$($sa.id)/tokens" -Headers $h -Body (@{
    name = "mcp-$(Get-Date -Format 'yyyyMMddHHmmss')"; secondsToLive = 0
  } | ConvertTo-Json)
if (-not $token.key) { throw "Grafana did not return a token key" }

$envFile = Join-Path $CredDir "grafana-dev.env"
@"
# Kind-fleet Grafana (bare FQDN) — generated by setup-grafana-dev-mcp.ps1
GRAFANA_URL=$GrafanaUrl
GRAFANA_SERVICE_ACCOUNT_TOKEN=$($token.key)
AM_GRAFANA_MCP_WRITE=0
"@ | Set-Content -Path $envFile -Encoding utf8
Write-Host "wrote $envFile"

# Smoke
$th = @{ Authorization = "Bearer $($token.key)" }
$ds = Invoke-RestMethod -Uri "$GrafanaUrl/api/datasources" -Headers $th
$boards = Invoke-RestMethod -Uri "$GrafanaUrl/api/search?type=dash-db&limit=50" -Headers $th
Write-Host "OK datasources=$($ds.Count) dashboards=$($boards.Count)"
Write-Host "Next: ensure Cursor mcpServers.grafana-dev -> $BinDir\grafana-dev-mcp.cmd then reload MCP."
Write-Host "Test plan: docs/kind-fleet-clusters/GRAFANA_FLEET_DEV.md"
